### ISSUE TITLE
crashes for me with current versions

### ISSUE THREAD

**Issue by bryanlarsen** [tomchentw/koa-webpack-dev#4]
I'm not sure if I'm doing something wrong, or I'm just using too new versions of webpack et al, but I'm getting this backtrace:

```
/vagrant/node_modules/webpack/lib/NormalModuleFactory.js:42
		var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");
		                      ^
TypeError: Cannot read property 'replace' of undefined
    at Tapable.<anonymous> (/vagrant/node_modules/webpack/lib/NormalModuleFactory.js:42:25)
    at Tapable.applyPluginsAsyncWaterfall (/vagrant/node_modules/webpack/node_modules/tapable/lib/Tapable.js:77:69)
    at Tapable.NormalModuleFactory.create (/vagrant/node_modules/webpack/lib/NormalModuleFactory.js:27:7)
    at Tapable.<anonymous> (/vagrant/node_modules/webpack/lib/Compilation.js:204:11)
    at /vagrant/node_modules/webpack/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/vagrant/node_modules/webpack/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/vagrant/node_modules/webpack/node_modules/async/lib/async.js:124:9)
    at Tapable.Compilation.addModuleDependencies (/vagrant/node_modules/webpack/lib/Compilation.js:175:8)
    at Tapable.Compilation.processModuleDependencies (/vagrant/node_modules/webpack/lib/Compilation.js:161:7)

```

io.js v1.5.1
webpack v1.7.3
babel 4.7.12
koa 0.18.1
react 0.12.2

**Comment by bryanlarsen** [comment]
Never mind, I wasn't loading my configuration properly.   Sorry.
